/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import abstracts.Plantable;
import control.ViewController;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Patrick
 */
public class CreateTimerView extends javax.swing.JDialog {

    private ViewController viewController;
    private SeedRegister seedRegister;
    private SeedBundleRegister seedBundleRegister;
    private SaplingRegister saplingRegister;
    private LivestockRegister livestockRegister;
    private TimerRegister timerRegister;
    private FavoriteRegister favoritRegister;

    /**
     * Creates new form CreateTimerView
     */
    public CreateTimerView(java.awt.Frame parent, boolean modal, ViewController viewController, SeedRegister seedRegister, SeedBundleRegister seedBundleRegister, SaplingRegister saplingRegister, LivestockRegister livestockRegister, TimerRegister timerRegister, FavoriteRegister favoritRegister) {
        super(parent, modal);
        initComponents();
        this.viewController = viewController;
        this.seedRegister = seedRegister;
        this.seedBundleRegister = seedBundleRegister;
        this.saplingRegister = saplingRegister;
        this.livestockRegister = livestockRegister;
        this.timerRegister = timerRegister;
        this.favoritRegister = favoritRegister;

        seedList.setModel(seedRegister.getListModel());
        seedbundleList.setModel(seedBundleRegister.getListModel());
        saplingList.setModel(saplingRegister.getListModel());
        livestockList.setModel(livestockRegister.getListModel());
    }

    private void clean() {
        seedList.clearSelection();
        seedbundleList.clearSelection();
        saplingList.clearSelection();
        livestockList.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        seedPane = new javax.swing.JPanel();
        seedScrollPane = new javax.swing.JScrollPane();
        seedList = new javax.swing.JList();
        seedbundlePane = new javax.swing.JPanel();
        seedbundleScrollPane = new javax.swing.JScrollPane();
        seedbundleList = new javax.swing.JList();
        saplingPane = new javax.swing.JPanel();
        saplingScrollPane = new javax.swing.JScrollPane();
        saplingList = new javax.swing.JList();
        livestockPane = new javax.swing.JPanel();
        livestockScrollPane = new javax.swing.JScrollPane();
        livestockList = new javax.swing.JList();
        toolPane = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteSelectedButton = new javax.swing.JButton();
        addToFavoritButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        mainPane.setLayout(new java.awt.GridLayout(1, 0));

        seedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seeds", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        seedList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        seedScrollPane.setViewportView(seedList);

        javax.swing.GroupLayout seedPaneLayout = new javax.swing.GroupLayout(seedPane);
        seedPane.setLayout(seedPaneLayout);
        seedPaneLayout.setHorizontalGroup(
            seedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seedPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        seedPaneLayout.setVerticalGroup(
            seedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seedPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPane.add(seedPane);

        seedbundlePane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seed bundles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        seedbundleList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seedbundleList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        seedbundleScrollPane.setViewportView(seedbundleList);

        javax.swing.GroupLayout seedbundlePaneLayout = new javax.swing.GroupLayout(seedbundlePane);
        seedbundlePane.setLayout(seedbundlePaneLayout);
        seedbundlePaneLayout.setHorizontalGroup(
            seedbundlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seedbundlePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seedbundleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        seedbundlePaneLayout.setVerticalGroup(
            seedbundlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seedbundlePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seedbundleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPane.add(seedbundlePane);

        saplingPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saplings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        saplingList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saplingList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        saplingScrollPane.setViewportView(saplingList);

        javax.swing.GroupLayout saplingPaneLayout = new javax.swing.GroupLayout(saplingPane);
        saplingPane.setLayout(saplingPaneLayout);
        saplingPaneLayout.setHorizontalGroup(
            saplingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saplingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saplingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        saplingPaneLayout.setVerticalGroup(
            saplingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saplingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saplingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPane.add(saplingPane);

        livestockPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livestock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        livestockList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        livestockList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        livestockScrollPane.setViewportView(livestockList);

        javax.swing.GroupLayout livestockPaneLayout = new javax.swing.GroupLayout(livestockPane);
        livestockPane.setLayout(livestockPaneLayout);
        livestockPaneLayout.setHorizontalGroup(
            livestockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livestockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livestockScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        livestockPaneLayout.setVerticalGroup(
            livestockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livestockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livestockScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPane.add(livestockPane);

        createButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createButton.setText("Create timer from selected");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        newButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newButton.setText("New plantable");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteSelectedButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteSelectedButton.setText("Delete selected");
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        addToFavoritButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addToFavoritButton.setText("Add selected to favorites");
        addToFavoritButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFavoritButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolPaneLayout = new javax.swing.GroupLayout(toolPane);
        toolPane.setLayout(toolPaneLayout);
        toolPaneLayout.setHorizontalGroup(
            toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSelectedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToFavoritButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        toolPaneLayout.setVerticalGroup(
            toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancelButton)
                    .addComponent(newButton)
                    .addComponent(deleteSelectedButton)
                    .addComponent(addToFavoritButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        viewController.setViewVisible(ViewController.NEWPLANTABLEVIEW, true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        List<Seed> seeds = seedList.getSelectedValuesList();
        List<SeedBundle> seedBundles = seedbundleList.getSelectedValuesList();
        List<Sapling> saplings = saplingList.getSelectedValuesList();
        List<Livestock> livestocks = livestockList.getSelectedValuesList();

        if (!seeds.isEmpty() || !seedBundles.isEmpty() || !saplings.isEmpty() || !livestocks.isEmpty()) {

            int n = JOptionPane.showConfirmDialog(this,
                    "Sure you want to delete selected plantables?\nTimers associated with it, will also be deleted!",
                    "Delete?",
                    JOptionPane.YES_NO_OPTION);

            if (n == 0) {
                Iterator<Seed> seedsList = seeds.iterator();
                Iterator<SeedBundle> seedBundlesList = seedBundles.iterator();
                Iterator<Sapling> saplingsList = saplings.iterator();
                Iterator<Livestock> livestocksList = livestocks.iterator();

                ArrayList<Timer> timerObjects = timerRegister.getObjects();
                ArrayList<Timer> timersToDestroy = new ArrayList<>();

                for (Timer t : timerObjects) {
                    Plantable p = t.getPlantable();

                    if (p instanceof Seed) {
                        Seed ss = (Seed) p;
                        for (Seed s : seeds) {
                            if (s.equals(ss)) {
                                timersToDestroy.add(t);
                            }
                        }
                    }
                    if (p instanceof SeedBundle) {
                        SeedBundle ss = (SeedBundle) p;
                        for (SeedBundle s : seedBundles) {
                            if (s.equals(ss)) {
                                timersToDestroy.add(t);
                            }
                        }
                    }
                    if (p instanceof Sapling) {
                        Sapling ss = (Sapling) p;
                        for (Sapling s : saplings) {
                            if (s.equals(ss)) {
                                timersToDestroy.add(t);
                            }
                        }
                    }
                    if (p instanceof Livestock) {
                        Livestock ss = (Livestock) p;
                        for (Livestock s : livestocks) {
                            if (s.equals(ss)) {
                                timersToDestroy.add(t);
                            }
                        }
                    }
                }

                Iterator<Timer> i = timersToDestroy.iterator();
                while (i.hasNext()) {
                    Timer t = i.next();
                    timerRegister.delete(t);
                }

                while (seedsList.hasNext()) {
                    Seed s = seedsList.next();
                    Iterator<Timer> timers = timerRegister.getObjects().iterator();
                    while (timers.hasNext()) {
                        Timer t = timers.next();
                        if (t.getPlantable().equals(s)) {
                            timers.remove();
                        }
                    }
                    seedRegister.delete(s);
                }

                while (seedBundlesList.hasNext()) {
                    SeedBundle s = seedBundlesList.next();
                    Iterator<Timer> timers = timerRegister.getObjects().iterator();
                    while (timers.hasNext()) {
                        Timer t = timers.next();
                        if (t.getPlantable().equals(s)) {
                            timers.remove();
                        }
                    }
                    seedBundleRegister.delete(s);
                }

                while (saplingsList.hasNext()) {
                    Sapling s = saplingsList.next();
                    Iterator<Timer> timers = timerRegister.getObjects().iterator();
                    while (timers.hasNext()) {
                        Timer t = timers.next();
                        if (t.getPlantable().equals(s)) {
                            timers.remove();
                        }
                    }
                    saplingRegister.delete(s);
                }

                while (livestocksList.hasNext()) {
                    Livestock s = livestocksList.next();
                    Iterator<Timer> timers = timerRegister.getObjects().iterator();
                    while (timers.hasNext()) {
                        Timer t = timers.next();
                        if (t.getPlantable().equals(s)) {
                            timers.remove();
                        }
                    }
                    livestockRegister.delete(s);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please choose something!",
                    "Choose!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        List<Seed> seeds = seedList.getSelectedValuesList();
        List<SeedBundle> seedBundles = seedbundleList.getSelectedValuesList();
        List<Sapling> saplings = saplingList.getSelectedValuesList();
        List<Livestock> livestocks = livestockList.getSelectedValuesList();

        if (!seeds.isEmpty() || !seedBundles.isEmpty() || !saplings.isEmpty() || !livestocks.isEmpty()) {

            Iterator<Seed> seedsList = seeds.iterator();
            Iterator<SeedBundle> seedBundlesList = seedBundles.iterator();
            Iterator<Sapling> saplingsList = saplings.iterator();
            Iterator<Livestock> livestocksList = livestocks.iterator();

            while (seedsList.hasNext()) {
                Seed s = seedsList.next();
                boolean inClimate = false;
                int n = JOptionPane.showConfirmDialog(
                        this,
                        "Is " + s.getName() + ", planted in the right climate?",
                        "Climate?",
                        JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    inClimate = true;
                }
                timerRegister.create(s, inClimate);
            }

            while (seedBundlesList.hasNext()) {
                SeedBundle s = seedBundlesList.next();
                boolean inClimate = false;
                int n = JOptionPane.showConfirmDialog(
                        this,
                        "Is " + s.getName() + ", planted in the right climate?",
                        "Climate?",
                        JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    inClimate = true;
                }
                timerRegister.create(s, inClimate);
            }

            while (saplingsList.hasNext()) {
                Sapling s = saplingsList.next();
                boolean inClimate = false;
                int n = JOptionPane.showConfirmDialog(
                        this,
                        "Is " + s.getName() + ", planted in the right climate?",
                        "Climate?",
                        JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    inClimate = true;
                }
                timerRegister.create(s, inClimate);
            }

            while (livestocksList.hasNext()) {
                Livestock s = livestocksList.next();
                boolean inClimate = false;
                int n = JOptionPane.showConfirmDialog(
                        this,
                        "Is " + s.getName() + ", planted in the right climate?",
                        "Climate?",
                        JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    inClimate = true;
                }
                timerRegister.create(s, inClimate);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please choose something!",
                    "Choose!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        clean();
    }//GEN-LAST:event_formWindowClosed

    private void addToFavoritButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFavoritButtonActionPerformed
        List<Seed> seeds = seedList.getSelectedValuesList();
        List<SeedBundle> seedBundles = seedbundleList.getSelectedValuesList();
        List<Sapling> saplings = saplingList.getSelectedValuesList();
        List<Livestock> livestocks = livestockList.getSelectedValuesList();

        if (!seeds.isEmpty() || !seedBundles.isEmpty() || !saplings.isEmpty() || !livestocks.isEmpty()) {

            Iterator<Seed> seedsList = seeds.iterator();
            Iterator<SeedBundle> seedBundlesList = seedBundles.iterator();
            Iterator<Sapling> saplingsList = saplings.iterator();
            Iterator<Livestock> livestocksList = livestocks.iterator();

            while (seedsList.hasNext()) {
                Seed s = seedsList.next();
                favoritRegister.create(s);
            }

            while (seedBundlesList.hasNext()) {
                SeedBundle s = seedBundlesList.next();
                favoritRegister.create(s);
            }

            while (saplingsList.hasNext()) {
                Sapling s = saplingsList.next();
                favoritRegister.create(s);
            }

            while (livestocksList.hasNext()) {
                Livestock s = livestocksList.next();
                favoritRegister.create(s);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please choose something!",
                    "Choose!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addToFavoritButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToFavoritButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JList livestockList;
    private javax.swing.JPanel livestockPane;
    private javax.swing.JScrollPane livestockScrollPane;
    private javax.swing.JPanel mainPane;
    private javax.swing.JButton newButton;
    private javax.swing.JList saplingList;
    private javax.swing.JPanel saplingPane;
    private javax.swing.JScrollPane saplingScrollPane;
    private javax.swing.JList seedList;
    private javax.swing.JPanel seedPane;
    private javax.swing.JScrollPane seedScrollPane;
    private javax.swing.JList seedbundleList;
    private javax.swing.JPanel seedbundlePane;
    private javax.swing.JScrollPane seedbundleScrollPane;
    private javax.swing.JPanel toolPane;
    // End of variables declaration//GEN-END:variables
}
