/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.FileHandler;
import control.ViewController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.TimerRegister;

/**
 *
 * @author Patrick
 */
public class MainView extends javax.swing.JFrame {
    
    private final ViewController viewController;
    private TimerRegister timerRegister;
    private FileHandler fileHandler;

    /**
     * Creates new form MainView
     * @param viewController
     * @param timerRegister
     */
    public MainView(ViewController viewController, TimerRegister timerRegister, FileHandler fileHandler) {
        initComponents();
        this.viewController = viewController;
        this.timerRegister = timerRegister;
        this.fileHandler = fileHandler;
        
        timersTable.setModel(timerRegister.getTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        toolPane = new javax.swing.JPanel();
        favoritesList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        quickAddButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        timersScrollPane = new javax.swing.JScrollPane();
        timersTable = new javax.swing.JTable();
        removeSelectedTimersButton = new javax.swing.JButton();
        toolBar = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        doShitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(aaft.AAFT.title);
        setIconImage(aaft.AAFT.icon);
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPane.setBackground(new java.awt.Color(153, 153, 153));

        toolPane.setBackground(new java.awt.Color(51, 51, 51));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        favoritesList.setViewportView(jList1);

        quickAddButton.setBackground(new java.awt.Color(51, 51, 51));
        quickAddButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quickAddButton.setText("Quick add");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Remove selected");

        javax.swing.GroupLayout toolPaneLayout = new javax.swing.GroupLayout(toolPane);
        toolPane.setLayout(toolPaneLayout);
        toolPaneLayout.setHorizontalGroup(
            toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(favoritesList)
                    .addComponent(quickAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        toolPaneLayout.setVerticalGroup(
            toolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(favoritesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quickAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        timersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Time remaining", "State"
            }
        ));
        timersScrollPane.setViewportView(timersTable);

        removeSelectedTimersButton.setBackground(new java.awt.Color(153, 153, 153));
        removeSelectedTimersButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeSelectedTimersButton.setText("Remove selected");
        removeSelectedTimersButton.setFocusable(false);
        removeSelectedTimersButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeSelectedTimersButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addComponent(removeSelectedTimersButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeSelectedTimersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addContainerGap())
        );

        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.add(filler1);

        doShitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doShitButton.setText("Do shit");
        doShitButton.setFocusable(false);
        doShitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doShitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        doShitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doShitButtonActionPerformed(evt);
            }
        });
        toolBar.add(doShitButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doShitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doShitButtonActionPerformed
        viewController.setViewVisible(ViewController.CREATETIMERVIEW, true);
    }//GEN-LAST:event_doShitButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            fileHandler.save();
        } catch (IOException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doShitButton;
    private javax.swing.JScrollPane favoritesList;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JButton quickAddButton;
    private javax.swing.JButton removeSelectedTimersButton;
    private javax.swing.JScrollPane timersScrollPane;
    private javax.swing.JTable timersTable;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JPanel toolPane;
    // End of variables declaration//GEN-END:variables
}
