/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ViewController;
import javax.swing.JOptionPane;
import model.LivestockRegister;
import model.SaplingRegister;
import model.SeedBundleRegister;
import model.SeedRegister;

/**
 *
 * @author Patrick
 */
public class NewPlantableView extends javax.swing.JDialog {

    private ViewController viewController;
    private SeedRegister seedRegister;
    private SeedBundleRegister seedBundleRegister;
    private SaplingRegister saplingRegister;
    private LivestockRegister livestockRegister;

    /**
     * Creates new form NewPlantable
     */
    public NewPlantableView(java.awt.Frame parent, boolean modal, ViewController viewController, SeedRegister seedRegister, SeedBundleRegister seedBundleRegister, SaplingRegister saplingRegister, LivestockRegister livestockRegister) {
        super(parent, modal);
        initComponents();
        this.viewController = viewController;
        this.seedRegister = seedRegister;
        this.seedBundleRegister = seedBundleRegister;
        this.saplingRegister = saplingRegister;
        this.livestockRegister = livestockRegister;
    }

    private boolean create() {
        String type = (String) typeCB.getSelectedItem();
        String name = nameTF.getText();
        String climate = (String) climateCB.getSelectedItem();
        String ds = dTF.getText();
        String hs = hTF.getText();
        String ms = mTF.getText();
        String ss = sTF.getText();
        if (ds.isEmpty()) {
            ds = "00";
        }
        if (hs.isEmpty()) {
            hs = "00";
        }
        if (ms.isEmpty()) {
            ms = "00";
        }
        if (ss.isEmpty()) {
            ss = "00";
        }
        if (!name.isEmpty()) {
            boolean create = true;
            try {
                int di = Integer.valueOf(ds);
                int hi = Integer.valueOf(hs);
                int mi = Integer.valueOf(ms);
                int si = Integer.valueOf(ss);

                long dl = di * 86400000;
                long hl = hi * 3600000;
                long ml = mi * 60000;
                long sl = si * 1000;

                long growthTime = dl + hl + ml + sl;

                if (create) {
                    switch (type) {
                        case "Seed":
                            seedRegister.create(name, growthTime, climate);
                            break;
                        case "SeedBundle":
                            seedBundleRegister.create(name, growthTime, climate);
                            break;
                        case "Sapling":
                            saplingRegister.create(name, growthTime, climate);
                            break;
                        case "Livestock":
                            livestockRegister.create(name, growthTime, climate);
                            break;
                    }
                    return true;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Dont write anything else than numbers in the time fields!",
                        "Woops!",
                        JOptionPane.ERROR_MESSAGE);
                create = false;
            }
            return false;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Fill out all fields!",
                    "Woops!",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void clean() {
        nameTF.setText("");
        dTF.setText("");
        hTF.setText("");
        mTF.setText("");
        sTF.setText("");
        typeCB.setSelectedIndex(0);
        climateCB.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        climateCB = new javax.swing.JComboBox();
        dTF = new javax.swing.JTextField();
        hTF = new javax.swing.JTextField();
        mTF = new javax.swing.JTextField();
        sTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox();
        createAndNextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Climate:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Growth time:");

        nameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        climateCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        climateCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Tropical", "Subarctic", "Arid", "Temperate" }));

        dTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dTFKeyReleased(evt);
            }
        });

        hTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hTFKeyReleased(evt);
            }
        });

        mTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mTFKeyReleased(evt);
            }
        });

        sTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sTFKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("D");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("H");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("M");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("S");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Type:");

        typeCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seed", "SeedBundle", "Sapling", "Livestock" }));

        createAndNextButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createAndNextButton.setText("Create and next");
        createAndNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAndNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createAndNextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTF)
                            .addComponent(climateCB, 0, 290, Short.MAX_VALUE)
                            .addGroup(mainPaneLayout.createSequentialGroup()
                                .addComponent(dTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(typeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(climateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton)
                    .addComponent(createAndNextButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if (create()) {
            dispose();
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void createAndNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAndNextButtonActionPerformed
        if (create()) {
            clean();
        }
    }//GEN-LAST:event_createAndNextButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        clean();
    }//GEN-LAST:event_formWindowClosed

    private void dTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dTFKeyReleased
        String s = dTF.getText();
        if (s.length() == 2) {
            dTF.requestFocus();
        }
        if (s.length() > 2) {
            dTF.setText(s.substring(0, s.length() - (s.length() - 2)));
        }
    }//GEN-LAST:event_dTFKeyReleased

    private void hTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hTFKeyReleased
        String s = hTF.getText();
        if (s.length() == 2) {
            hTF.requestFocus();
        }
        if (s.length() > 2) {
            hTF.setText(s.substring(0, s.length() - (s.length() - 2)));
        }
    }//GEN-LAST:event_hTFKeyReleased

    private void mTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mTFKeyReleased
        String s = mTF.getText();
        if (s.length() == 2) {
            mTF.requestFocus();
        }
        if (s.length() > 2) {
            mTF.setText(s.substring(0, s.length() - (s.length() - 2)));
        }
    }//GEN-LAST:event_mTFKeyReleased

    private void sTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sTFKeyReleased
        String s = sTF.getText();
        if (s.length() == 2) {
            sTF.requestFocus();
        }
        if (s.length() > 2) {
            sTF.setText(s.substring(0, s.length() - (s.length() - 2)));
        }
    }//GEN-LAST:event_sTFKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox climateCB;
    private javax.swing.JButton createAndNextButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dTF;
    private javax.swing.JTextField hTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mTF;
    private javax.swing.JPanel mainPane;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField sTF;
    private javax.swing.JComboBox typeCB;
    // End of variables declaration//GEN-END:variables
}
